src/net.cpp

upnp patch

---

Axe-qt.pro
src/net.cpp
src/qt/macnotificationhandler.h
src/qt/macnotificationhandler.mm

macOS update

---

Axe-qt.pro
doc/readme-qt.rst
src/net.cpp
src/qt/macnotificationhandler.h
src/qt/macnotificationhandler.mm
src/qt/notificator.cpp

macOS patch

---

src/qt/bitcoingui.cpp
src/qt/clientmodel.cpp
src/qt/clientmodel.h
src/qt/forms/rpcconsole.ui
src/qt/locale/bitcoin_ru.ts
src/qt/rpcconsole.cpp
src/qt/rpcconsole.h

RPC console now shows:
* inbound / outbound connections
* OpenSSL BerkleyDB versions
History behavior improved, type switched to Widget

RPC console upgrade

---

src/qt/bitcoingui.cpp
src/qt/bitcoingui.h
src/qt/forms/optionsdialog.ui
src/qt/forms/rpcconsole.ui
src/qt/guiutil.cpp
src/qt/guiutil.h
src/qt/locale/bitcoin_ru.ts
src/qt/optionsdialog.cpp
src/qt/optionsdialog.h
src/qt/rpcconsole.cpp
src/qt/rpcconsole.h
src/util.cpp

Now `axe.conf` file will be created automatically during launch. Easy access was added through **Debug window**.

configuration file tweaks

---

src/main.cpp

flying delorean transaction exploit fix

zero cost mempool memory exhaustion exploit

---

contrib/gitian-build.sh
src/init.cpp
src/main.cpp
src/main.h
src/rpcblockchain.cpp
src/rpcrawtransaction.cpp
src/rpcwallet.cpp
src/util.h

fix DoS vulnerability by flooding orphan mempools

---

contrib/gitian-build.sh
src/init.cpp
src/qt/transactiontablemodel.cpp
src/qt/transactiontablemodel.h
src/qt/transactionview.cpp
src/qt/transactionview.h
src/qt/walletmodel.cpp
src/qt/walletmodel.h
src/rpcblockchain.cpp
src/rpcrawtransaction.cpp
src/rpcwallet.cpp
src/util.h
src/wallet.cpp
src/wallet.h

clear orphans option

---

_config.yml
src/chainparams.cpp

checkpoint

---

contrib/gitian-build.py

build script fixes

---

share/qt/Info.plist.in

waiting for Qt to add the `dark mode` support

skip dark mode in qt

---

depends/Makefile
depends/hosts/default.mk
depends/packages/chia_bls.mk
depends/packages/gmp.mk
depends/packages/openssl.mk

https://github.com/bitcoin/bitcoin/pull/12474

Fix depends for armv7l

---

src/chainparams.cpp
src/spork.cpp

this will go into master as axe `v1.3.1` so spin `gov` deployment

Set superblocks activation

---

src/netbase.cpp

https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2019-November/017453.html

Merge #11397: net: Improve and document SOCKS code

---

src/chainparams.cpp
src/chainparamsbase.cpp

Change regtest and devnet p2p/rpc ports

---

test/functional/llmq-chainlocks.py
test/functional/llmq-is-cl-conflicts.py
test/functional/test_framework/test_framework.py

Backport https://github.com/dashpay/dash/pull/3129 and https://github.com/dashpay/dash/pull/3130

Backport fixes for Chainlock tests and add more logging to AxeTestFramework

---

src/addrman.h
src/privatesend/privatesend-client.cpp
src/qt/bitcoingui.cpp
src/qt/bitcoingui.h
src/qt/coincontroldialog.cpp
src/qt/sendcoinsdialog.cpp
src/qt/transactiontablemodel.cpp
src/qt/transactiontablemodel.h
src/qt/walletmodel.cpp
src/qt/walletmodel.h
src/rpc/masternode.cpp
src/rpc/rpcevo.cpp
src/wallet/coincontrol.h
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h
test/functional/net.py

This backports https://github.com/dashpay/dash/pull/3169, https://github.com/dashpay/dash/pull/3171, https://github.com/dashpay/dash/pull/3170, https://github.com/dashpay/dash/pull/3172, https://github.com/dashpay/dash/pull/3174.

Backport GUI fixes, bitcoin#11252, coin type via CCoinControl, net.py test fixes

---

src/Makefile.qt.include
src/qt/axe_locale.qrc
src/qt/axestrings.cpp
src/qt/locale/axe_de.ts
src/qt/locale/axe_en.ts
src/qt/locale/axe_es.ts
src/qt/locale/axe_fi.ts
src/qt/locale/axe_fr.ts
src/qt/locale/axe_it.ts
src/qt/locale/axe_ja.ts
src/qt/locale/axe_ko.ts
src/qt/locale/axe_pl.ts
src/qt/locale/axe_pt.ts
src/qt/locale/axe_ro.ts
src/qt/locale/axe_ru.ts
src/qt/locale/axe_sk.ts
src/qt/locale/axe_th.ts
src/qt/locale/axe_tr.ts
src/qt/locale/axe_vi.ts
src/qt/locale/axe_zh_CN.ts
src/qt/locale/axe_zh_TW.ts

* en
* ru
* fi
* ko, vi
* it, pl, sk
* fix fi
* es, fr, zh_TW
* de, nl
* Add ro
* pt, tr, zh_CN
* th
* ja

Pull upstream translations 201909

---

src/masternode/activemasternode.cpp
src/pow.cpp
src/privatesend/privatesend-client.cpp
src/rpc/blockchain.cpp
src/rpc/governance.cpp
src/rpc/masternode.cpp
src/rpc/mining.cpp
src/rpc/rpcquorums.cpp
src/wallet/wallet.cpp
src/zmq/zmqpublishnotifier.cpp

Backport https://github.com/dashpay/dash/pull/3191, https://github.com/dashpay/dash/pull/3193, https://github.com/dashpay/dash/pull/3195, https://github.com/dashpay/dash/pull/3196, https://github.com/dashpay/dash/pull/3198, https://github.com/dashpay/dash/pull/3194.

Partial PoW refactoring, fixes for RPC, logs, GOV, mixing

---

src/qt/res/css/dark.css
src/qt/sendcoinsdialog.cpp
src/qt/sendcoinsdialog.h

Also some fixes for dark theme.

Tweak "Send" popup and refactor related code a bit

---

src/spork.cpp

This PR makes the test stable green.
Thanks for contributing!

Test stable fix

---

.tx/config
src/qt/locale/axe_ar.ts
src/qt/locale/axe_bg.ts
src/qt/locale/axe_de.ts
src/qt/locale/axe_es.ts
src/qt/locale/axe_fi.ts
src/qt/locale/axe_fr.ts
src/qt/locale/axe_it.ts
src/qt/locale/axe_ja.ts
src/qt/locale/axe_ko.ts
src/qt/locale/axe_nl.ts
src/qt/locale/axe_pl.ts
src/qt/locale/axe_pt.ts
src/qt/locale/axe_ro.ts
src/qt/locale/axe_ru.ts
src/qt/locale/axe_sk.ts
src/qt/locale/axe_th.ts
src/qt/locale/axe_tr.ts
src/qt/locale/axe_vi.ts
src/qt/locale/axe_zh_CN.ts
src/qt/locale/axe_zh_TW.ts

Update tx resources

---

src/privatesend/privatesend-client.cpp
src/qt/transactionrecord.cpp

Few tweaks for MakeCollateralAmounts

Few tweaks for MakeCollateralAmounts

---

src/evo/mnauth.cpp
src/llmq/quorums_utils.cpp
src/llmq/quorums_utils.h
src/net_processing.cpp

also add minor correction in `net_processing.cpp `

Deterministically choose which peers to drop on duplicate MNAUTH

---

src/rpc/misc.cpp
src/spork.cpp
src/spork.h

Very rough, but better than approaching this vertically.

Add spork tables for testnet/regtest/devnet
